export enum ItemCategory {
  ADVENTURING_GEAR = 'adventuring-gear',
  AMMUNITION = 'ammunition',
  ARCANE_FOCI = 'arcane-foci',
  ARMOR = 'armor',
  ARTISANS_TOOL = 'artisans-tool',
  DRUIDIC_FOCI = 'druidic-foci',
  EQUIPMENT_PACK = 'equipment-pack',
  GAMING_SET = 'gaming-set',
  HEAVY_ARMOR = 'heavy-armor',
  HOLY_SYMBOL = 'holy-symbol',
  KIT = 'kit',
  LAND_VEHICLE = 'land-vehicle',
  LIGHT_ARMOR = 'light-armor',
  MARTIAL_MELEE_WEAPON = 'martial-melee-weapon',
  MARTIAL_RANGED_WEAPON = 'martial-ranged-weapon',
  MARTIAL_WEAPON = 'martial-weapon',
  MAGIC_ITEM = 'magic-item',
  MEDIUM_ARMOR = 'medium-armor',
  MELEE_WEAPON = 'melee-weapon',
  MOUNT_OR_OTHER_ANIMAL = 'mount-or-other-animal',
  MOUNT_OR_VEHICLE = 'mount-or-vehicle',
  MUSICAL_INSTRUMENT = 'musical-instrument',
  OTHER_TOOL = 'other-tool',
  POTION = 'potion',
  RANGED_WEAPON = 'ranged-weapon',
  RING = 'ring',
  ROD = 'rod',
  SCROLL = 'scroll',
  SHIELD = 'shield',
  SIMPLE_MELEE_WEAPON = 'simple-melee-weapon',
  SIMPLE_RANGED_WEAPON = 'simple-ranged-weapon',
  SIMPLE_WEAPON = 'simple-weapon',
  STAFF = 'staff',
  STANDARD_GEAR = 'standard-gear',
  TACK_HARNESS_OR_DRAWN_VEHICLE = 'tack-harness-or-drawn-vehicle',
  TOOL = 'tool',
  VEHICLE = 'vehicle',
  WAND = 'wand',
  WATERBORNE_VEHICLE = 'waterborne-vehicle',
  WEAPON = 'weapon',
  WONDROUS_ITEM = 'wondrous-item'
}

export const SECONDARY_CATEGORIES = [
  ItemCategory.MARTIAL_WEAPON,
  ItemCategory.MARTIAL_MELEE_WEAPON,
  ItemCategory.MARTIAL_RANGED_WEAPON,
  ItemCategory.MAGIC_ITEM,
  ItemCategory.MEDIUM_ARMOR,
  ItemCategory.MELEE_WEAPON,
  ItemCategory.RANGED_WEAPON,
  ItemCategory.SIMPLE_MELEE_WEAPON,
  ItemCategory.SIMPLE_RANGED_WEAPON,
  ItemCategory.SIMPLE_WEAPON
] as ItemCategory[]
