version: '3.6'

volumes:
  data:

services:
  db:
    image: mariadb:10.6.16
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: dmtool
      MARIADB_USER: development
      MARIADB_PASSWORD: development123
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
